### ISSUE TITLE
Compatibility with offline models?

### ISSUE THREAD

**Issue by luisvalenzuelar** [Invalid-Null/AutomaticReviewGeneration#1]
Hi there. 

Any chance this can be implemented with offline models like Llama-3 via LMStudio? IMO the API requirements is too much for the majority of case users (researchers). At best we have a pro account but that does not include API. 

Best

**Comment by Invalid-Null** [comment]
Thank you for your excellent suggestion. I completely understand your concerns about the API requirements.

Indeed, my method can accept any open-source model as a backend as long as it provides an API in OpenAI format. To my knowledge, several LLM deployment projects like LMStudio, ollama, Fastchat, or comprehensive projects like swift and LangChatChat can support deploying a local HTTP server, providing ports similar to http://127.0.0.1:7861 or http://0.0.0.0:7861.

To use these local deployments with my tool, you would need to:

1. In the GUI interface, go to LLM Options → Add to OpenAI-compatible API Url List.
2. Add the corresponding IP and address, such as http://127.0.0.1:7861 (if you're deploying the LLM locally) or http://remote-IP-address:7861 (if you're deploying on a remote server and accessing it locally).
3. In the Add to OpenAI-compatible API Key List option, add the corresponding API Key (if there is one; if not, you can enter a random string).

You can find a visual guide for these steps in our documentation: https://github.com/Invalid-Null/AutomaticReviewGeneration/blob/main/doc/GUI_tutorial.md#6-large-language-model-options-configuration

After adding these details, you can test the connection to your LLM. If it returns the corresponding model's self-description, the connection is successful, and you can use the related features normally.

I'm planning to add functionality in the code for my program to deploy local LLMs and support access directly. However, due to other work commitments, this feature might take some time to implement - likely between one week to a month, at least.

Thank you again for raising this issue. I hope my work can be helpful to you and other researchers who prefer or need to use offline models. If you have any further questions or need more clarification, please don't hesitate to ask.

**Comment by luisvalenzuelar** [comment]
Amazing, thanks! I will implement and see how it goes. All the best with the project!

**Comment by WSC741606** [comment]
Thank you for your enthusiasm! If you encounter any issues during implementation or use, please don't hesitate to reach out to me. I'll be sure to follow up promptly. Have a nice day! :)

**Comment by Invalid-Null** [comment]
Thank you for your enthusiasm! If you encounter any issues during implementation or use, please don't hesitate to reach out to me. I'll be sure to follow up promptly. Have a nice day! :)
